export const FeaturedDeals = [
  {
    id: 0,
    title: "Burger & Chips Platter",
    image: "/feature_0.png",
    tag: "/discount_tag.png",
    old_price: "12,500.00",
    new_price: "8,750.00",
    brand: "Jazzy’s Burger",
    location: "Lagos, Nigeria",
    rating: "4.5",
    rating_count: 4,
  },
  {
    id: 1,
    title: "Veggie Noodles & Egg",
    image: "/feature_1.png",
    tag: "/discount_tag.png",
    old_price: "12,500.00",
    new_price: "8,750.00",
    brand: "Kilimanjaro",
    location: "Lagos, Nigeria",
    rating: "5.0",
    rating_count: 5,
  },
  {
    id: 2,
    title: "Chicken Shawarma",
    image: "/feature_2.png",
    tag: "/discount_tag.png",
    old_price: "12,500.00",
    new_price: "8,750.00",
    brand: "Drizzy’s Bites",
    location: "Lagos, Nigeria",
    rating: "3.2",
    rating_count: 3,
  },
  {
    id: 3,
    title: "Burger & Chips Platter",
    image: "/feature_0.png",
    tag: "/discount_tag.png",
    old_price: "12,500.00",
    new_price: "8,750.00",
    brand: "Jazzy’s Burger",
    location: "Lagos, Nigeria",
    rating: "5.0",
    rating_count: 5,
  },
  {
    id: 4,
    title: "Veggie Noodles & Egg",
    image: "/feature_1.png",
    tag: "/discount_tag.png",
    old_price: "12,500.00",
    new_price: "8,750.00",
    brand: "Kilimanjaro",
    location: "Lagos, Nigeria",
    rating: "4.5",
    rating_count: 4,
  },
  {
    id: 5,
    title: "Chicken Shawarma",
    image: "/feature_2.png",
    tag: "/discount_tag.png",
    old_price: "12,500.00",
    new_price: "8,750.00",
    brand: "Drizzy’s Bites",
    location: "Lagos, Nigeria",
    rating: "5.0",
    rating_count: 5,
  },
  {
    id: 6,
    title: "Burger & Chips Platter",
    image: "/feature_0.png",
    tag: "/discount_tag.png",
    old_price: "12,500.00",
    new_price: "8,750.00",
    brand: "Jazzy’s Burger",
    location: "Lagos, Nigeria",
    rating: "4.5",
    rating_count: 4,
  },
  {
    id: 7,
    title: "Veggie Noodles & Egg",
    image: "/feature_1.png",
    tag: "/discount_tag.png",
    old_price: "12,500.00",
    new_price: "8,750.00",
    brand: "Kilimanjaro",
    location: "Lagos, Nigeria",
    rating: "4.5",
    rating_count: 4,
  },
];

export const CouponDeals = [
  {
    id: 0,
    title: "25% off",
    bg: "/mac_bg.svg",
    logo: "/kfc.png",
    brand: "KFC",
    divider: "/divider_white.png",
  },
  {
    id: 1,
    title: "35% off",
    bg: "/drizzy_bg.svg",
    logo: "/drizzy.png",
    brand: "Drizzy's bite",
    divider: "/divider_white.png",
  },
  {
    id: 2,
    title: "15% off",
    bg: "/kfc_bg.svg",
    logo: "/mac.png",
    brand: "McDonalds",
    divider: "/divider_white.png",
  },
  {
    id: 3,
    title: "25% off",
    bg: "/cr_bg.svg",
    logo: "/cr.png",
    brand: "Chicken Republic",
    divider: "/divider_white.png",
  },
  {
    id: 4,
    title: "25% off",
    bg: "/jazzy_bg.svg",
    logo: "/jazzy.png",
    brand: "KFC",
    divider: "/divider_black.png",
  },
  {
    id: 5,
    title: "25% off",
    bg: "/mac_bg.svg",
    logo: "/kfc.png",
    brand: "KFC",
    divider: "/divider_white.png",
  },
];

export const InfoDetails = [
  {
    id: 0,
    image: "/info_3.svg",
    title: "subscribe",
    content:
      "Select a subscription plan and enjoy full access to available discount, deals and coupons on all featured restaurants",
  },
  {
    id: 1,
    image: "/info_2.svg",
    title: "explore",
    content:
      "Browse through the list of restaurants offering discounts that match your criteria & Select",
  },
  {
    id: 2,
    image: "/info_1.svg",
    title: "enjoy",
    content:
      "Once you've chosen a restaurant, simply mention the discount when you dine in to enjoy your savings!.",
  },
];

export const heroBgSlides = [
  {
    id: 0,
    background: "/kuwiya_bg.png",
    title: "welcome to kuwiya.",
    text: "Subscribe to get up to 30% discount on all featured restaurant this weekend",
  },
  {
    id: 1,
    background: "/bg_1.png",
    title: "eat today, live another day.",
    text: "Get your favorite meal without breaking the bank.",
  },
  {
    id: 2,
    background: "/bg_2.png",
    title: "save up to 50% off every time you eat out.",
    text: "Discount on all featured restaurant.",
  },
];

export const FeaturedResturants = [
  {
    id: 0,
    label: "Drizzy's Bites",
    text: "Lorem ipsum dolor sit amet consectetur. Dolor et diam egestas",
    distance: "1KM away",
    logo: "/drizzy.webp",
  },
  {
    id: 1,
    label: "Drizzy's Bites",
    text: "Lorem ipsum dolor sit amet consectetur. Dolor et diam egestas",
    distance: "1KM away",
    logo: "/drizzy.webp",
  },
  {
    id: 2,
    label: "Drizzy's Bites",
    text: "Lorem ipsum dolor sit amet consectetur. Dolor et diam egestas",
    distance: "1KM away",
    logo: "/drizzy.webp",
  },
  {
    id: 3,
    label: "Drizzy's Bites",
    text: "Lorem ipsum dolor sit amet consectetur. Dolor et diam egestas",
    distance: "1KM away",
    logo: "/drizzy.webp",
  },
  {
    id: 4,
    label: "Drizzy's Bites",
    text: "Lorem ipsum dolor sit amet consectetur. Dolor et diam egestas",
    distance: "1KM away",
    logo: "/drizzy.webp",
  },
];

export const availableDiscounts = [
  {
    id: 1,
    discPercentage: 85,
    mealImageUrl: "/allYummy.png",
    restaurantLogoUrl: "/discount-theplace.png",
    mealName: "Jollof Rice and Chicken",
    restaurantName: "The Place",
    price: 1500,
    duration: "12:00-01:00 PM",
    rating: 4.5,
    reviewCount: 483,
  },
  {
    id: 2,
    discPercentage: 80,
    mealImageUrl: "/allYummy2.png",
    restaurantLogoUrl: "/discount-mr-biggs.png",
    mealName: "Fried Rice and Chicken",
    restaurantName: "Mr Bigg's",
    price: 1500,
    duration: "12:00-01:00 PM",
    rating: 4.5,
    reviewCount: 483,
  },
  {
    id: 3,
    discPercentage: 75,
    mealImageUrl: "/allYummy.png",
    restaurantLogoUrl: "/discount-item7.png",
    mealName: "Special Rice and Chicken",
    restaurantName: "Item7",
    price: 1500,
    duration: "12:00-01:00 PM",
    rating: 4.5,
    reviewCount: 483,
  },
  {
    id: 4,
    discPercentage: 65,
    mealImageUrl: "/allYummy2.png",
    restaurantLogoUrl: "/discount-theplace.png",
    mealName: "Eba & Egusi",
    restaurantName: "The place",
    price: 1500,
    duration: "12:00-01:00 PM",
    rating: 4.5,
    reviewCount: 483,
  },
  {
    id: 5,
    discPercentage: 65,
    mealImageUrl: "/allYummy.png",
    restaurantLogoUrl: "/discount-theplace.png",
    mealName: "Eba & Egusi",
    restuarantName: "The place",
    price: 1500,
    duration: "12:00-01:00 PM",
    rating: 4.5,
    reviewCount: 483,
  },
];

export const couponMarketplace = [
  {
    id: 1,
    restName: "item7",
    restLogo: "/discount-mr-biggs.png",
    mealName: "Chicken & Fries",
    originalPrice: 1500,
    priceOff: 500,
    mealImage: "/allYummy.png",
    mealInfo:
      "3 pieces of Chicken Hot & Crispy / Original, 1 Regular Chips & 1 Drink",
    couponCode: "ABC",
    couponNum: "123",
    duration: "12:00-01:00 pm",
    rating: 4.5,
    reviewCount: 483,
  },
  {
    id: 2,
    restName: "KFC",
    restLogo: "/discount-item7.png",
    mealName: "Chicken & Fries",
    originalPrice: 1500,
    priceOff: 500,
    mealImage: "/allYummy2.png",
    mealInfo:
      "3 pieces of Chicken Hot & Crispy / Original, 1 Regular Chips & 1 Drink",
    couponCode: "ABC",
    couponNum: "123",
    duration: "12:00-01:00 pm",
    rating: 4.5,
    reviewCount: 483,
  },
  {
    id: 3,
    restName: "The place",
    restLogo: "/discount-theplace.png",
    mealName: "Chicken & Fries",
    originalPrice: 1500,
    priceOff: 500,
    mealImage: "/allYummy.png",
    mealInfo:
      "3 pieces of Chicken Hot & Crispy / Original, 1 Regular Chips & 1 Drink",
    couponCode: "ABC",
    couponNum: "123",
    duration: "12:00-01:00 pm",
    rating: 4.5,
    reviewCount: 483,
  },
  {
    id: 4,
    restName: "KFC",
    restLogo: "/discount-item7.png",
    mealName: "Chicken & Fries",
    originalPrice: 1500,
    priceOff: 500,
    mealImage: "/allYummy2.png",
    mealInfo:
      "3 pieces of Chicken Hot & Crispy / Original, 1 Regular Chips & 1 Drink",
    couponCode: "ABC",
    couponNum: "123",
    duration: "12:00-01:00 pm",
    rating: 4.5,
    reviewCount: 483,
  },
];

export const Restaurants = [
  {
    id: 0,
    image: "/place.svg",
    title: "The Place - Jerusalem Bus Stop",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 1,
    image: "/mc.svg",
    title: "McDonald's - Allen",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 2,
    image: "/dominoes.svg",
    title: "Domino's pizza",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 3,
    image: "/biggs.svg",
    title: "Mr Bigg’s- Allen Bus Stop",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 4,
    image: "/kfc.svg",
    title: "Mr Bigg’s- Allen Bus Stop",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 5,
    image: "/cr.svg",
    title: "Chicken Republic - Ikotun",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 6,
    image: "/item.svg",
    title: "The Place - Jerusalem Bus Stop",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 7,
    image: "/killimanjaro.svg",
    title: "Mr Bigg’s- Allen Bus Stop",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 8,
    image: "/tantalizer.svg",
    title: "Chicken Republic - Ikotun",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 0,
    image: "/mc.svg",
    title: "The Place - Jerusalem Bus Stop",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 1,
    image: "/biggs.svg",
    title: "McDonald's - Allen",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 2,
    image: "/place.svg",
    title: "Domino's pizza",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 3,
    image: "/item.svg",
    title: "Mr Bigg’s- Allen Bus Stop",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 4,
    image: "/cr.svg",
    title: "Mr Bigg’s- Allen Bus Stop",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 5,
    image: "/tantalizer.svg",
    title: "Chicken Republic - Ikotun",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 6,
    image: "/dominoes.svg",
    title: "The Place - Jerusalem Bus Stop",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 7,
    image: "/kfc.svg",
    title: "Mr Bigg’s- Allen Bus Stop",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 8,
    image: "/cr.svg",
    title: "Chicken Republic - Ikotun",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 0,
    image: "/dominoes.svg",
    title: "The Place - Jerusalem Bus Stop",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 1,
    image: "/kfc.svg",
    title: "McDonald's - Allen",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 2,
    image: "/mc.svg",
    title: "Domino's pizza",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 3,
    image: "/place.svg",
    title: "Mr Bigg’s- Allen Bus Stop",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 4,
    image: "/cr.svg",
    title: "Mr Bigg’s- Allen Bus Stop",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 5,
    image: "/biggs.svg",
    title: "Chicken Republic - Ikotun",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 6,
    image: "/item.svg",
    title: "The Place - Jerusalem Bus Stop",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 7,
    image: "/killimanjaro.svg",
    title: "Mr Bigg’s- Allen Bus Stop",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
  {
    id: 8,
    image: "/item.svg",
    title: "Chicken Republic - Ikotun",
    distance: "10 km",
    ratings: "4.5 (483)",
    status: "open",
  },
];

export const restaurantFeatured = [
  {
    id: 1,
    title: "Burger & Chips Platter",
    image: "/feature_0.png",
    old_price: "12,500.00",
    new_price: "8,750.00",
    brand: "Jazzy’s Burger",
    location: "Lagos, Nigeria",
    rating: "4.5",
    rating_count: 4,
  },
  {
    id: 2,
    title: "Chicken Shawarma",
    image: "/feature_2.png",

    old_price: "12,500.00",
    new_price: "8,750.00",
    brand: "Drizzy’s Bites",
    location: "Lagos, Nigeria",
    rating: "3.2",
    rating_count: 3,
  },
];

export const restaurantCoupon = [
  {
    id: 1,
    discPercentage: 15,
    restLogo: "/placeLogo.png",
    restName: "The Place",
    restAddress: "45 Isaac John St, GRA 101233, Ikeja.",
    duration: "12:00-01:00 pm",
  },
  {
    id: 2,
    discPercentage: 15,
    restLogo: "/placeLogo.png",
    restName: "The Place",
    restAddress: "45 Isaac John St, GRA 101233, Ikeja.",
    duration: "12:00-01:00 pm",
  },
  {
    id: 3,
    discPercentage: 15,
    restLogo: "/placeLogo.png",
    restName: "The Place",
    restAddress: "45 Isaac John St, GRA 101233, Ikeja.",
    duration: "12:00-01:00 pm",
  },
];

export const customersReviews = [
  {
    id: 1,
    customerImage: "/review1.png",
    customerName: "john doe",
    customerTexts:
      "Lorem ipsum dolor sit amet consectetur. Dolor et diam egestas condimentum egestas nisi nibh dignissim. Placerat id sit mattis donec pharetra.",
    rating_count: 5.0,
  },
  {
    id: 2,
    customerImage: "/review2.png",
    customerName: "john doe",
    customerTexts:
      "Lorem ipsum dolor sit amet consectetur. Dolor et diam egestas condimentum egestas nisi nibh dignissim. Placerat id sit mattis donec pharetra.",
    rating_count: 5.0,
  },
  {
    id: 3,
    customerImage: "/review3.png",
    customerName: "john doe",
    customerTexts:
      "Lorem ipsum dolor sit amet consectetur. Dolor et diam egestas condimentum egestas nisi nibh dignissim. Placerat id sit mattis donec pharetra.",
    rating_count: 5.0,
  },
  {
    id: 4,
    customerImage: "/review4.png",
    customerName: "john doe",
    customerTexts:
      "Lorem ipsum dolor sit amet consectetur. Dolor et diam egestas condimentum egestas nisi nibh dignissim. Placerat id sit mattis donec pharetra.",
    rating_count: 5.0,
  },
];
