export const FeaturedDeals = [
  {
    id: 0,
    title: "Burger & Chips Platter",
    image: "/feature_0.png",
    tag: "/discount_tag.png",
    old_price: "12,500.00",
    new_price: "8,750.00",
    brand: "Jazzy’s Burger",
    location: "Lagos, Nigeria",
    rating: "4.5",
    rating_count: 4,
  },
  {
    id: 1,
    title: "Veggie Noodles & Egg",
    image: "/feature_1.png",
    tag: "/discount_tag.png",
    old_price: "12,500.00",
    new_price: "8,750.00",
    brand: "Kilimanjaro",
    location: "Lagos, Nigeria",
    rating: "5.0",
    rating_count: 5,
  },
  {
    id: 2,
    title: "Chicken Shawarma",
    image: "/feature_2.png",
    tag: "/discount_tag.png",
    old_price: "12,500.00",
    new_price: "8,750.00",
    brand: "Drizzy’s Bites",
    location: "Lagos, Nigeria",
    rating: "3.2",
    rating_count: 3,
  },
  {
    id: 3,
    title: "Burger & Chips Platter",
    image: "/feature_0.png",
    tag: "/discount_tag.png",
    old_price: "12,500.00",
    new_price: "8,750.00",
    brand: "Jazzy’s Burger",
    location: "Lagos, Nigeria",
    rating: "5.0",
    rating_count: 5,
  },
  {
    id: 4,
    title: "Veggie Noodles & Egg",
    image: "/feature_1.png",
    tag: "/discount_tag.png",
    old_price: "12,500.00",
    new_price: "8,750.00",
    brand: "Kilimanjaro",
    location: "Lagos, Nigeria",
    rating: "4.5",
    rating_count: 4,
  },
  {
    id: 5,
    title: "Chicken Shawarma",
    image: "/feature_2.png",
    tag: "/discount_tag.png",
    old_price: "12,500.00",
    new_price: "8,750.00",
    brand: "Drizzy’s Bites",
    location: "Lagos, Nigeria",
    rating: "5.0",
    rating_count: 5,
  },
  {
    id: 6,
    title: "Burger & Chips Platter",
    image: "/feature_0.png",
    tag: "/discount_tag.png",
    old_price: "12,500.00",
    new_price: "8,750.00",
    brand: "Jazzy’s Burger",
    location: "Lagos, Nigeria",
    rating: "4.5",
    rating_count: 4,
  },
  {
    id: 7,
    title: "Veggie Noodles & Egg",
    image: "/feature_1.png",
    tag: "/discount_tag.png",
    old_price: "12,500.00",
    new_price: "8,750.00",
    brand: "Kilimanjaro",
    location: "Lagos, Nigeria",
    rating: "4.5",
    rating_count: 4,
  },
];

export const CouponDeals = [
  {
    id: 0,
    title: "25% off",
    bg: "/mac_bg.svg",
    logo: "/kfc.png",
    brand: "KFC",
    divider: "/divider_white.png",
  },
  {
    id: 1,
    title: "35% off",
    bg: "/drizzy_bg.svg",
    logo: "/drizzy.png",
    brand: "Drizzy's bite",
    divider: "/divider_white.png",
  },
  {
    id: 2,
    title: "15% off",
    bg: "/kfc_bg.svg",
    logo: "/mac.png",
    brand: "McDonalds",
    divider: "/divider_white.png",
  },
  {
    id: 3,
    title: "25% off",
    bg: "/cr_bg.svg",
    logo: "/cr.png",
    brand: "Chicken Republic",
    divider: "/divider_white.png",
  },
  {
    id: 4,
    title: "25% off",
    bg: "/jazzy_bg.svg",
    logo: "/jazzy.png",
    brand: "KFC",
    divider: "/divider_black.png",
  },
  {
    id: 5,
    title: "25% off",
    bg: "/mac_bg.svg",
    logo: "/kfc.png",
    brand: "KFC",
    divider: "/divider_white.png",
  },
];

export const InfoDetails = [
  {
    id: 0,
    image: "/info_3.svg",
    title: "subscribe",
    content:
      "Select a subscription plan and enjoy full access to available discount, deals and coupons on all featured restaurants",
  },
  {
    id: 1,
    image: "/info_2.svg",
    title: "explore",
    content:
      "Browse through the list of restaurants offering discounts that match your criteria & Select",
  },
  {
    id: 2,
    image: "/info_1.svg",
    title: "enjoy",
    content:
      "Once you've chosen a restaurant, simply mention the discount when you dine in to enjoy your savings!.",
  },
];

export const heroBgSlides = [
  {
    id: 0,
    background: "/kuwiya_bg.png",
    title: "welcome to kuwiya.",
    text: "Subscribe to get up to 30% discount on all featured restaurant this weekend",
  },
  {
    id: 1,
    background: "/bg_1.png",
    title: "eat today, live another day.",
    text: "Get your favorite meal without breaking the bank.",
  },
  {
    id: 2,
    background: "/bg_2.png",
    title: "save up to 50% off every time you eat out.",
    text: "Discount on all featured restaurant.",
  },
];

export const FeaturedResturants = [
  {
    id: 0,
    label: "Drizzy's Bites",
    text: "Lorem ipsum dolor sit amet consectetur. Dolor et diam egestas",
    distance: "1KM away",
    logo: "/drizzy.webp",
  },
  {
    id: 1,
    label: "Drizzy's Bites",
    text: "Lorem ipsum dolor sit amet consectetur. Dolor et diam egestas",
    distance: "1KM away",
    logo: "/drizzy.webp",
  },
  {
    id: 2,
    label: "Drizzy's Bites",
    text: "Lorem ipsum dolor sit amet consectetur. Dolor et diam egestas",
    distance: "1KM away",
    logo: "/drizzy.webp",
  },
  {
    id: 3,
    label: "Drizzy's Bites",
    text: "Lorem ipsum dolor sit amet consectetur. Dolor et diam egestas",
    distance: "1KM away",
    logo: "/drizzy.webp",
  },
  {
    id: 4,
    label: "Drizzy's Bites",
    text: "Lorem ipsum dolor sit amet consectetur. Dolor et diam egestas",
    distance: "1KM away",
    logo: "/drizzy.webp",
  },
];
